### ISSUE TITLE
Improve security by removing password from commandline 

### ISSUE THREAD

**Issue by mjavier2k** [mjavier2k/solidfire-exporter#25]
see comment on https://github.com/prometheus/docs/pull/1683

Possible solution is to use a config file  like the following

```
endpoint: https://192.168.1.2/json-rpc/11.3
auth:
   username: username
   password: password 
port: 1234
insecure: true
timeout: 30
```
